spring:
  application:
    name: retreever-example

server:
  port: 9000

logging:
  level:
    org.springframework.security: DEBUG

# Retreever Environment Configuration
retreever:
  dev:
    allow-cross-origin:
      - http://localhost:5173
  auth:
    username: Admin
    password: Admin@123
  env:
    variables:

      - name: access-token
        source:
          request:
            endpoints:
              - /api/v1/public/login
              - /api/v1/public/login/refresh
            method: post
            response:
              body-attribute-path: data.access_token

      - name: refresh-token
        source:
          request:
            endpoints:
            - /api/v1/public/login
            - /api/v1/public/login/refresh
            method: post
            response:
              body-attribute-path: data.refresh_token

      - name: device-id
        source:
          value: device-web-001
